apiVersion: apps/v1
kind: Deployment
metadata:
  name: lung-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lung-app
  template:
    metadata:
      labels:
        app: lung-app
    spec:
      containers:
        - name: lung-app
          image: researchselvi/lung-app:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000
