apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app-es
  namespace: argocd
    
spec:
  project: default
  source:
    repoURL: https://github.com/research-selvi-datascience/MLOPs-Lung-Capacity-Prediction.git
    targetRevision: feature/continuous-training
    path: k8s   
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true