name: Continuous Training Pipeline



on:
  push:
    branches:
      - feature/continuous-training

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training
        run: python -m preprocess_data.train

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: models/